In [378]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ["A", "B", "C"], index= ["D", "E", "F"])

df.head() shows first 5 rows by default, can also take arguments

In [379]:
df.head()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

We can see giving 2 as an argument to head() function now displays 2 rows only.

In [380]:
df.head(2)

   A  B  C
D  1  2  3
E  4  5  6

df.tail() shows bottom 5 rows by default and can also take arguments.

In [381]:
df.tail()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

Giving tail() an argument of 1 shows the bottom row of the data or array set.

In [382]:
df.tail(1)

   A  B  C
F  7  8  9

df.columns shows the column names as specified or just [1,2,3] by default.

In [383]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

df directly displays the whole array at once.

In [384]:
df

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

df.index shows the row namings or [1,2,3] by default.

In [385]:
df.index

Index(['D', 'E', 'F'], dtype='str')

Displays the index as a list

In [386]:
df.index.tolist()

['D', 'E', 'F']

Displays columns as a list

In [387]:
df.columns.tolist()

['A', 'B', 'C']

Displays information about all the rows

In [388]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, D to F
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

Gives information about all the numbers in the column

In [389]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

How many unique values are in a column

In [390]:
df.nunique()

A    3
B    3
C    3
dtype: int64

Find specifically for A column

In [391]:
df["A"].unique()

array([1, 4, 7])

Gives the size of the dataframe

In [392]:
df.shape

(3, 3)

Number of cells in the dataframe

In [393]:
df.size

9

To get data from a folder ont he desktop

In [394]:
#pd.read_csv('./foldercoffee.csv')

To get data from a raw file from GitHub

In [395]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

Tested out all the previous functions on the new dataframe.

In [396]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [397]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [398]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [399]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 659.0 bytes

In [400]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [401]:
coffee.index

RangeIndex(start=0, stop=14, step=1)

In [402]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='str')

**Multiple different extensions are used other than csv. Feather and Parquet are also used which store the same data in relatively smaller size. We can also import excel files using pd.excel and adding some py libraries**

In [403]:
import pandas as pd
results = pd.read_parquet('results.parquet')
#olymp = pd.read_excel('olympics-data.xlsx')
bios = pd.read_csv('bios.csv')

In [404]:
results.head()
#olymp.head()
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

Accessing Data with Pandas

In [405]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

Tail gives bottom 5 lines or the number mentioned in brackets

In [406]:
coffee.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

Random values from the dataset as many as mentioned in brackets

In [407]:
coffee.sample(5)

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
9     Friday       Latte          35
13    Sunday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35

LOC function can be used to get a particular row

In [408]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

Slicing and selecting of rows or a range of rows is also possible

Putting field name or columns name to filter out

In [409]:
coffee.loc[0:3, "Day"]
coffee.loc[0:3, "Coffee Type"]
coffee.loc[6:7, ["Units Sold", "Day"]]

   Units Sold       Day
6          40  Thursday
7          30  Thursday

ILOC:

Uses index numbers instead of columns names

In [410]:
coffee.iloc[:5, [0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

We basically swapped out the index column with days column which changes the column 0 now if we see the dataset it will have changed

In [411]:
#coffee.index  = coffee["Day"]

We can see how the index column is now replaced with the days column

In [412]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

EXERCISE ON LOC AND ILOC

In [413]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [414]:
bios.iloc[0:9, [1,2]]

                    name   born_date
0  Jean-François Blanchy  1886-12-12
1         Arnaud Boetsch  1969-04-01
2           Jean Borotra  1898-08-13
3        Jacques Brugnon  1895-05-11
4           Albert Canet  1878-04-17
5      Nicolas Chatelain  1970-01-13
6          Patrick Chila  1969-11-27
7           Henri Cochet  1901-12-14
8          Marcel Cousin  1896-08-04

In [415]:
bios.loc[0:5, ['name', 'born_country']]

                    name born_country
0  Jean-François Blanchy          FRA
1         Arnaud Boetsch          FRA
2           Jean Borotra          FRA
3        Jacques Brugnon          FRA
4           Albert Canet          GBR
5      Nicolas Chatelain          FRA

In [416]:
bios.iloc[-5:, [0,1,2,3]]

        athlete_id                 name   born_date        born_city
145495      149222    Polina Luchnikova  2002-01-30            Serov
145496      149223  Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224      Yuliya Smirnova  1998-05-08           Kotlas
145498      149225       André Foussard  1899-05-19            Niort
145499      149814        Bill Phillips  1913-07-15     Dulwich Hill

In [417]:
bios.loc[bios["height_cm"]>200, ['name', 'height_cm']]

                      name  height_cm
1080        Bozhil Lozanov      208.0
1673      Alexis Rubalcaba      204.0
2647         Milan Šrejber      203.0
2827    Nik'oloz Deriugini      206.0
2832         Elşad Qadaşev      205.0
...                    ...        ...
143784  Daniel Miklasevich      203.0
143833  Garrett Muagututia      205.0
143834         Kyle Ensing      201.0
143835         Mitch Stahl      203.0
143919   Emerson Rodríguez      204.0

[1219 rows x 2 columns]

In [418]:
bios.loc[(bios["born_country"] == "FRA") & (bios["height_cm"] > 190), ['name', 'born_country', 'height_cm']]

                      name born_country  height_cm
2974       Patrice Aouissi          FRA      192.0
5640      Philippe Baillet          FRA      193.0
5647     Christian Baltzer          FRA      192.0
5703          Éric Beugnot          FRA      200.0
5704        Gregor Beugnot          FRA      192.0
...                    ...          ...        ...
139364  Guerschon Yabusele          FRA      207.0
139365      Moustapha Fall          FRA      218.0
139368     Vincent Poirier          FRA      213.0
139466     Trévor Clévenot          FRA      199.0
144642       Bastien Midol          FRA      191.0

[244 rows x 3 columns]

Modify dataset

You can see how we can modify the data as well with use of loc functions

In [419]:
#coffee.loc[1, "Units Sold"] = 10
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

ACCESSING DATA BY GRAB COLUMNS AND ROWS

In [420]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

Sorting them by units sold and in descending order

Descending by making ascending = false and ascending my making ascending = true

Multiple columns by using square brackets as always

For multiple columns we can use [0,1] etc to define the order we want for different columns and a combination of both will be the output

In [421]:
#coffee.sort_values(["Units Sold", "Coffee Type"], ascending=True)
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[1,0])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
0      Monday    Espresso          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

For loop iteration but not recommended to use everytime better to use iloc or loc or at func.

In [422]:
for index, row in coffee.iterrows():
    print(index)
    print("Units Sold")
    print("\n")

0
Units Sold


1
Units Sold


2
Units Sold


3
Units Sold


4
Units Sold


5
Units Sold


6
Units Sold


7
Units Sold


8
Units Sold


9
Units Sold


10
Units Sold


11
Units Sold


12
Units Sold


13
Units Sold

FILTERING DATA

In [423]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [424]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

Both give same output we can use brackets once inside the loc func or use it separately but with nested brackets

In [425]:
bios.loc[bios["height_cm"] > 210][['name', 'born_country']]
bios.loc[bios["height_cm"] > 210, ['name', 'born_country']]

                         name born_country
5089       Viktor Pankrashkin          RUS
5572          Santiago Aldama          ESP
5583     Paulinho Villas Boas          BRA
5599        Vladimir Andreyev          RUS
5609          Franjo Arapović          NaN
...                       ...          ...
140298       Aaron Geramipoor          GBR
141018          Yuta Watanabe          JPN
142044          Jahlil Okafor          USA
142930             Mike Tobey          USA
143712           JaVale McGee          USA

[150 rows x 2 columns]

Cannot use == here coz there will be no one named exactly Keith

contains() has more parameters like case which can allow searching with lowercase and uppercase letters without an issue

In [426]:
bios[bios["name"].str.contains("Aaron|Patrick", case = False, regex = True)]
bios[bios["name"].str.startswith("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN

We can use this to avoid writing long expressions for bios which may create confusion. We pass the query as a string in single quotes

In [427]:
bios.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

Adding/Removing Columns

In [428]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

We can add a new column this way

In [429]:
coffee['price'] = 5
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25      5
1      Monday       Latte          15      5
2     Tuesday    Espresso          30      5
3     Tuesday       Latte          20      5
4   Wednesday    Espresso          35      5
5   Wednesday       Latte          25      5
6    Thursday    Espresso          40      5
7    Thursday       Latte          30      5
8      Friday    Espresso          45      5
9      Friday       Latte          35      5
10   Saturday    Espresso          45      5
11   Saturday       Latte          35      5
12     Sunday    Espresso          45      5
13     Sunday       Latte          35      5

Using conditions to add prices for different coffees

Used NumPy to help us read and scan through data quickly to calculate conditions

In [430]:
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25      5       3.99
1      Monday       Latte          15      5       5.99
2     Tuesday    Espresso          30      5       3.99
3     Tuesday       Latte          20      5       5.99
4   Wednesday    Espresso          35      5       3.99
5   Wednesday       Latte          25      5       5.99
6    Thursday    Espresso          40      5       3.99
7    Thursday       Latte          30      5       5.99
8      Friday    Espresso          45      5       3.99
9      Friday       Latte          35      5       5.99
10   Saturday    Espresso          45      5       3.99
11   Saturday       Latte          35      5       5.99
12     Sunday    Espresso          45      5       3.99
13     Sunday       Latte          35      5       5.99

Eliminate columns drop method will only show the dataset in that way by dropping that column or row or whatev it doesnt change the dataset at the origin

In [431]:
#coffee.drop(columns= "price")

Inplace = true will remove the column permanently from the database

We can do same thing if we reassign coffee as the dropped version of coffee that gets printed

In [ ]:
#coffee.drop(columns= ['price'], inplace=True)
#coffee = coffee.drop(columns= ['price'])

coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25      5       3.99
1      Monday       Latte          15      5       5.99
2     Tuesday    Espresso          30      5       3.99
3     Tuesday       Latte          20      5       5.99
4   Wednesday    Espresso          35      5       3.99
5   Wednesday       Latte          25      5       5.99
6    Thursday    Espresso          40      5       3.99
7    Thursday       Latte          30      5       5.99
8      Friday    Espresso          45      5       3.99
9      Friday       Latte          35      5       5.99
10   Saturday    Espresso          45      5       3.99
11   Saturday       Latte          35      5       5.99
12     Sunday    Espresso          45      5       3.99
13     Sunday       Latte          35      5       5.99

Cloning a datafile by simply just equating them will lead to another new variable pointing at the same space 

For example:

coffee_new = coffee(this will just point to coffee again)

if we want a copy we need to use copy func

coffee_new = coffee.copy()

In [434]:
coffee_new = coffee.copy()

Made it so that coffee_new has a price column but coffee doesnt

In [439]:
#coffee.drop(columns= ['price'], inplace=True)

It shows as we want it to

In [441]:
coffee_new
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99