<a href="https://colab.research.google.com/github/KingGuy123/ML-Practice/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ["A", "B", "C"], index= ["D", "E", "F"])

df.head() shows first 5 rows by default, can also take arguments

In [4]:
df.head()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

We can see giving 2 as an argument to head() function now displays 2 rows only.

In [5]:
df.head(2)

   A  B  C
D  1  2  3
E  4  5  6

df.tail() shows bottom 5 rows by default and can also take arguments.

In [6]:
df.tail()

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

Giving tail() an argument of 1 shows the bottom row of the data or array set.

In [7]:
df.tail(1)

   A  B  C
F  7  8  9

df.columns shows the column names as specified or just [1,2,3] by default.

In [8]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

df directly displays the whole array at once.

In [9]:
df

   A  B  C
D  1  2  3
E  4  5  6
F  7  8  9

df.index shows the row namings or [1,2,3] by default.

In [10]:
df.index

Index(['D', 'E', 'F'], dtype='str')

Displays the index as a list

In [11]:
df.index.tolist()

['D', 'E', 'F']

Displays columns as a list

In [12]:
df.columns.tolist()

['A', 'B', 'C']

Displays information about all the rows

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, D to F
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

Gives information about all the numbers in the column

In [14]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

How many unique values are in a column

In [15]:
df.nunique()

A    3
B    3
C    3
dtype: int64

Find specifically for A column

In [16]:
df["A"].unique()

array([1, 4, 7])

Gives the size of the dataframe

In [17]:
df.shape

(3, 3)

Number of cells in the dataframe

In [18]:
df.size

9

To get data from a folder ont he desktop

In [19]:
#pd.read_csv('./foldercoffee.csv')

To get data from a raw file from GitHub

In [20]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

Tested out all the previous functions on the new dataframe.

In [21]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [22]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [23]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [24]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 659.0 bytes

In [25]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [26]:
coffee.index

RangeIndex(start=0, stop=14, step=1)

In [27]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='str')

**Multiple different extensions are used other than csv. Feather and Parquet are also used which store the same data in relatively smaller size. We can also import excel files using pd.excel and adding some py libraries**

In [28]:
import pandas as pd
results = pd.read_parquet('results.parquet')
#olymp = pd.read_excel('olympics-data.xlsx')
bios = pd.read_csv('bios.csv')

In [29]:
results.head()
#olymp.head()
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

Accessing Data with Pandas

In [30]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

Tail gives bottom 5 lines or the number mentioned in brackets

In [31]:
coffee.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

Random values from the dataset as many as mentioned in brackets

In [32]:
coffee.sample(5)

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
13     Sunday       Latte          35
8      Friday    Espresso          45
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35

LOC function can be used to get a particular row

In [39]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

Slicing and selecting of rows or a range of rows is also possible

Putting field name or columns name to filter out

In [61]:
coffee.loc[0:3, "Day"]
coffee.loc[0:3, "Coffee Type"]
coffee.loc[6:7, ["Units Sold", "Day"]]

   Units Sold       Day
6          40  Thursday
7          30  Thursday

ILOC:

Uses index numbers instead of columns names